### PR TITLE
Fix Swift documentation

### PR DESCRIPTION
**Pull request by danqing**
The class is `TOCropViewController`, not `CropViewController`.

### CODE REVIEW

**Comment by yarodevuci** [comment]
any merging ?

**Comment by TimOliver** [comment]
Sorry folks. This is incorrect. When working in Swift, the library is renamed to `CropViewController`. The sample code is already correct.

`TOCropViewController` is only when working in Objective-C. If you're having to call it `TOCropViewController` in code, you're not using the Swift version.

Thanks for the PR!

**Comment by danqing** [comment]
How do I use the swift version? I'm writing swift code myself and there doesn't seem to be `CropViewController` class.

**Comment by danqing** [comment]
Oh I think it may be that I use Carthage. Does Carthage come with the swift wrapper?

**Pull request closed without merging**
