### PR TITLE
Jk memory leak bug fixing

### PR DESCRIPTION
**Pull request by huang-kun**
You forget to call UIGraphicsEndImageContext() after image drawing. It will cause leak.

### CODE REVIEW

**Comment by TimOliver** [comment]
Oh wow! Blimey! Nicely caught! Thanks for that!

**Comment by huang-kun** [comment]
Hi Tim

When will you update the cocoapods ?

**Comment by TimOliver** [comment]
I'll try and do that in an hour or so. :)

**Comment by huang-kun** [comment]
There is a mistake on setRotateClockwiseButtonHidden: implementation on TOCropToolbar.m

Mistake:

if (_rotateClockwiseButton == NO)

Fix:

if (_rotateClockwiseButtonHidden == NO)

Unfortunately, my MacBook is out of power and I can not pull request recently. Please fix it when you have time and don't forget the cocoapods updates.

Thanks

> 在 2016年1月28日，16:06，Tim Oliver <notifications@github.com> 写道：
> 
> I'll try and do that in an hour or so. :)
>

**Comment by TimOliver** [comment]
Umm, I can't find anything wrong with that one... that's supposed to be working as intended. The idea is that the counter clockwise button is visible by default, but the clockwise one needs to be expicitly made visible via a setting.

I'll test it some more later, but for the time being, I just pushed the Pod!

**Pull request merged**
