### PR TITLE
presetSquare not always square

### PR DESCRIPTION
**Pull request by trr-amsiq**
the frame returned is now always square if ```presetSquare``` is used.

To reproduce use 
```
let toCropViewController = TOCropViewController(image: image)
        toCropViewController.delegate = self
        
        toCropViewController.rotateButtonsHidden = false
        toCropViewController.rotateClockwiseButtonHidden = false
        
        toCropViewController.aspectRatioPreset = .presetSquare
        toCropViewController.aspectRatioLockEnabled = true
        toCropViewController.resetAspectRatioEnabled = false
        
        self.present(toCropViewController, animated: true, completion: nil)
```

with image
img_0043

### CODE REVIEW

**Comment by tdnl** [comment]
Thumbs up for the square dimension. However, when cropping a image without moving the square box, the cropRect's "y" coordinate seems incorrect.

## Screenshot

squarecrop

## How to reproduce
- Open the cropper with a simulator, and open the same image as the screenshot above (it should be in the in the library by default). 
- Do not move the crop box and press done.

See how the "y" coordinate is < 0.

**Comment by tdnl** [comment]
No... I've been trying to install the library manually, or using your fork in my podfile but it would either fail to run, or just crash after pressing the "Done" button 😕

**Comment by tdnl** [comment]
Alright, apologize for the delay. I made my own fork, integrated your changes and successfully ran it on my phone.

The issue that I was talking earlier only happened on landscape images. Basically, when you first open the cropper, don't move anything and just press Done, if the cropper takes the entire height of the image, the result image will be shifted a little bit. 

Here is the rect that I received:
`{
        "height": 2325,
        "width": 2325,
        "y": -5,
        "x": 381
    }`

The size is a square, but the image is shifted a little bit to the bottom.

**Comment by TimOliver** [comment]
Thanks for the PR @trr-amsiq! This looks good to me! 

If there are test steps that can reliably reproduce that offset issue, it might be better to track the whole thing in a new issue.

**Pull request merged**
