### PR TITLE
TitleLabel text can be set now

### PR DESCRIPTION
**Pull request by Renan-B-Dias**
Hi! Regarding issue #241, I've implemented a 'fix' for it. I tried to take 'setDoneButtonTitle' and 'setCancelButtonTitle' as an example of how to do it (since I'm not very familiar with Objective-C). Unfortunately I couldn't test on an iPad but I did test it on my iPhone 7.

### CODE REVIEW

**Comment by TimOliver** [comment]
Hi @Renan-B-Dias!

Thanks for the PR! Um, but `setTitle` in Objective-C is exactly the same as calling `viewController.title = @"Foo"` (They're synthesised accessors. Swift got rid of them probably for a very good reason. XD). Why is this needed exactly?

**Comment by TimOliver** [comment]
Sorry for the incredibly long delay. Like I said before, this probably isn't needed since you can set `title` directly and capture the string from there. There's not really a need to have a separate property for this. :)

**Comment by Renan-B-Dias** [comment]
Hi Tim! Sorry for not answearing you sooner, it’s been a couple of long and crazy months here. By the time that I used you Pod I couldn’t set its viewsController by using ‘viewControllee.title = “Foo”’, but I’ll be refactoring my projects code soon enough so I’ll take a better look on how to use it like you said. Thank you so much for answearing me and sorry again for the delay I took to answearing back.

**Comment by TimOliver** [comment]
Hi @Renan-B-Dias! No problems! Likewise! I've been really busy this year.

Ahh okay. I fixed that in the latest release I published yesterday. Setting the `title` property of `CropViewController` will forward it to the internal `TOCropViewController` now. Hopefully that will fix it. :)

**Pull request closed without merging**
