### PR TITLE
Add public `commitCurrentCrop` function to expose private `doneButtonTapped` function

### PR DESCRIPTION
**Pull request by aizatomar**
Hello again!

The exposing was simple but I tried my best to write the documentation to something similar to `resetCropViewLayout` function. Since this is a small PR and I do want to expose the `cancelButtonTapped` function to public as well. Should I create a separate PR for cancel function or can I just add that change into this PR as well?

Let me know yah. :)

### CODE REVIEW

**Comment by aizatomar** [comment]
Forgot to add `;` in previous commit :( too much Swift.

**Comment by TimOliver** [comment]
Hahaha! It's not the first time someone who was still thinking in Swift has committed some code here. 🤣

Looks good! Although like I mentioned really briefly last night, I was thinking `doneButtonTapped` as a name isn't really explicit enough.

If it's not too much trouble, I was thinking maybe make a new method called `commitCurrentCrop` and then link that to `doneButtonTapped` internally.

What do you think about that? :)

**Comment by aizatomar** [comment]
Ah I see. So just to confirm my understanding. Wrap the private `doneButtonTapped` function with a public interfacing function called `commitCurrentCrop`. Is that it? I can do that. No problem. :)

**Comment by aizatomar** [comment]
Oh how about the documentation? Let me know if I need to edit that as well yah.

**Comment by TimOliver** [comment]
Yep! You got it! That's all! :D

Uhh, nah. The documentation you already wrote is good enough as it is! Thanks for that! 😁

**Comment by aizatomar** [comment]
Ok done! :)

**Comment by TimOliver** [comment]
Fantastic! Thanks so much Aizat! :D

**Comment by aizatomar** [comment]
No problem! :)

**Pull request merged**
