### PR TITLE
Added Portuguese (Brazil) translations

### PR DESCRIPTION
**Pull request by BrunoVillanova**

### CODE REVIEW

**Comment by TimOliver** [comment]
Awesome! Thank you so much for that!

**Comment by BrunoVillanova** [comment]
Thank you for the great work on this project!

**Comment by adrianodiasx93** [comment]
@TimOliver & @BrunoVillanova 
Here seems that Portuguese-BR is still not working.
I am using this lib in my swift project as a carthage dependency (linking the binary and importing it on code). I tried the last release and the master. Something I might be forgetting?

**Comment by TimOliver** [comment]
Is it just Portuguese-BR that's just borked? Or is it other languages too? I can't imagine all of the other languages have been broken in Carthage all this time and no one else has noticed.

**Pull request merged**
