### PR TITLE
Added circular cropping mode

### PR DESCRIPTION
**Pull request by alibasta**
Added TOCropViewControllerAspectRatioCircular to show a circular mask
while cropping.

### CODE REVIEW

**Comment by TimOliver** [comment]
Thanks a lot for that Alexander!

I was actually planning on doing this a bit of a different way. I was thinking of actually making a proper 'style' for circular portrait mode, because it means you can ditch a lot of the additional set-up if you know the aspect ratio can never change. Also... that API wording might be a little confusing because a 'circular' aspect ratio isn't really technically possible!

I'll merge it into a local branch and change it slightly before I merge it in. :)

**Comment by zhuozhihao** [comment]
If the picture has become a circle, it will be more perfect

**Comment by TimOliver** [comment]
Alrighty. I actually ended up modifying this a lot more than I thought (actually had quite a bit of fun), and I just merged my changes in.

* I used a `CAShapeLayer` mask instead of `cornerRadius` since I discovered the corner radius feature doesn't produce a perfect circle (probably the [iOS 7 rounding effect](http://www.mani.de/backstage/?p=483))
* I made the circular cropper a deeply integrated mode that disables the grid overlay, and behaves a little differently than the normal cropper in most cases.
* I also added a delegate that clips the resulting image to a circle too. :)

Just before signing off, thanks again for submitting a PR @alibasta, but please do test them a little more thoroughly before submitting. :) I discovered this PR was broken if you tapped the 'reset' button, or even just presented it while the device was in landscape mode. 

That being said, I could have easily broken it myself, so feel free to test it out yourself and see what you think! :)

**Comment by hainhathoang88** [comment]
Hi @TimOliver , How can we achieve this behavior in recent build version?

**Pull request merged**
