### PR TITLE
Now building with Swift 5 and updated README.md

### PR DESCRIPTION
**Pull request by OkiRules**
CropViewController is now being build with Swift 5. Also, the README.md now includes all examples in Swift.

Thanks!

### CODE REVIEW

**Comment by TimOliver** [comment]
Oh nice! Thanks for the PR @OkiRules!

Uhhh, this commit log is a bit of a mess though. GitHub is saying 95 files were changed. How did you do that? 😅

**Comment by OkiRules** [comment]
Sorry! I'm not that experienced with Pull Requests! 😅
I hope that all the changes are OK though...

Thanks!

**Comment by yarodevuci** [comment]
@TimOliver 

> Oh nice! Thanks for the PR @OkiRules!
> 
> Uhhh, this commit log is a bit of a mess though. GitHub is saying 95 files were changed. How did you do that? 😅

Probably automatic conversion ?! Can you merge this?

**Comment by danqing** [comment]
Looks like you need to change file mode from 755 back to 644.

**Comment by TimOliver** [comment]
Okay! I had some time free this weekend so I managed to go through this PR and cleaned it up.

I made sure your commits remained intact @OkiRules, so your GitHub account now shows you're a contributor to this project. :)

There's still a few more PRs I need to go through, so I'll do a new release when they're finished.

Thanks again for the help!

**Comment by OkiRules** [comment]
Thanks @TimOliver!

**Pull request merged**
