### PR TITLE
Fix privacy manifest missing key 'NSPrivacyCollectedDataType'

### PR DESCRIPTION
**Pull request by p-nicolaou**
This will allow Privacy Report to be generated without any errors about missing keys

### CODE REVIEW

**Review by LFMAKER — APPROVED** [review]

**Comment by LFMAKER** [comment]
@TimOliver, could you please merge this?

**Comment by TimOliver** [comment]
Oh thanks so much for this @p-nicolaou! I was gonna ask that if you're in a position to verify the manifest, a PR instead of me guessing would be greatly appreciated. I'll merge it now, but it'll have to be a little while before I can cut a new release.

**Comment by TimOliver** [comment]
@LFMAKER Respectfully, I do not appreciate being pinged in multiple issues. Please don't do that again.

**Comment by LFMAKER** [comment]
> @LFMAKER Respectfully, I do not appreciate being pinged in multiple issues. Please don't do that again.

Respectfully, I just tagged you in an issue that impacts thousands of projects and in the PR that addresses it; you're complaining about meaningless things. But I respect that and assure you that I won't comment further on this project.

**Comment by TimOliver** [comment]
@LFMAKER I'm trying my best to maintain this library in my spare time, for free. Rude, entitled engineers like yourself are why open source maintainers are burning out. Thanks for not commenting again.

**Comment by LFMAKER** [comment]
> I'm trying my best to maintain this library in my spare time, for free. Rude, entitled engineers like yourself are why open source maintainers are burning out. Thanks for not commenting again.

I understand your dedication to maintaining this library in your spare time and free, and I appreciate the effort you put into it. My intention in tagging you was to ensure that the issue could be addressed before Apple's deadline of May 1st. I apologize if my comments came across as rude. It was not my intention.

Reflecting on my words, I believe that projects like this, which have a positive impact on the market, indeed need community support. I hope I can help by contributing to this project. Let's stay in touch, and again, sorry for anything.

**Comment by skylarbarrera** [comment]
following here for a release

**Comment by saraff13** [comment]
@TimOliver When can we get a release for this?

**Pull request merged**
